# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1479874256);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1479874376);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1479906296);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 1479874616);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1479874136);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1479895616);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1479874496);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1479905923103");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1479907793103");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1479906204543");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1479909804543");
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161115214506");
user_pref("browser.slowStartup.averageTime", 6440);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20161115214506");
user_pref("browser.startup.homepage_override.mstone", "45.5.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1479829486665");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1479873788234");
user_pref("datareporting.policy.firstRunTime", "1479743086664");
user_pref("datareporting.sessions.current.activeTicks", 266);
user_pref("datareporting.sessions.current.firstPaint", 4587);
user_pref("datareporting.sessions.current.main", 527);
user_pref("datareporting.sessions.current.sessionRestored", 5247);
user_pref("datareporting.sessions.current.startTime", "1479873772972");
user_pref("datareporting.sessions.current.totalTime", 33319);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-fr@firefox-esr.mozilla.org\":{\"version\":\"45.5.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox-esr/browser/extensions/langpack-fr@firefox-esr.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.5.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1479874261);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.5.0");
user_pref("extensions.lastPlatformVersion", "45.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1479273689000}},\"app-global\":{\"langpack-fr@firefox-esr.mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/langpack-fr@firefox-esr.mozilla.org.xpi\",\"e\":true,\"v\":\"45.5.0\",\"st\":1479262689000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.5.0\",\"st\":1479273688000}}}");
user_pref("gecko.buildID", "20161115214506");
user_pref("gecko.mstone", "45.5.0");
user_pref("idle.lastDailyNotification", 1479874133);
user_pref("media.gmp-manager.buildID", "20161115214506");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1479874133);
user_pref("places.history.expiration.transient_current_max_pages", 26369);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1479874133);
user_pref("toolkit.startup.last_success", 1479873773);
user_pref("toolkit.telemetry.cachedClientID", "d8ecf0d5-14dd-4ac8-8e41-b84fc32e7e88");
user_pref("toolkit.telemetry.previousBuildID", "20161115214506");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
